name: deployDev
concurrency: dev
run-name: ${{ github.actor }} run this workflow

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE_NAME: ${{ github.repository }}
  APP_NAME: devfrugi
  SLOT_NAME: production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: buildAndPush
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev.${{ github.run_number }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
      - name: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev.${{ github.run_number }}
